//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPowerStations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowerStations_datEntities : DbContext
    {
        public PowerStations_datEntities()
            : base("name=PowerStations_datEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PowerReading00> PowerReading00 { get; set; }
        public virtual DbSet<PowerReading01> PowerReading01 { get; set; }
        public virtual DbSet<PowerReading02> PowerReading02 { get; set; }
        public virtual DbSet<PowerReading03> PowerReading03 { get; set; }
        public virtual DbSet<PowerReading04> PowerReading04 { get; set; }
        public virtual DbSet<PowerReading05> PowerReading05 { get; set; }
        public virtual DbSet<PowerReading06> PowerReading06 { get; set; }
        public virtual DbSet<PowerReading07> PowerReading07 { get; set; }
        public virtual DbSet<PowerReading08> PowerReading08 { get; set; }
        public virtual DbSet<PowerReading09> PowerReading09 { get; set; }
        public virtual DbSet<PowerReading10> PowerReading10 { get; set; }
        public virtual DbSet<PowerReading11> PowerReading11 { get; set; }
        public virtual DbSet<PowerReading12> PowerReading12 { get; set; }
        public virtual DbSet<PowerReading13> PowerReading13 { get; set; }
        public virtual DbSet<PowerReading14> PowerReading14 { get; set; }
        public virtual DbSet<PowerReading15> PowerReading15 { get; set; }
        public virtual DbSet<PowerReading16> PowerReading16 { get; set; }
        public virtual DbSet<PowerReading17> PowerReading17 { get; set; }
        public virtual DbSet<PowerReading18> PowerReading18 { get; set; }
        public virtual DbSet<PowerReading19> PowerReading19 { get; set; }
        public virtual DbSet<PowerReading20> PowerReading20 { get; set; }
        public virtual DbSet<PowerReading21> PowerReading21 { get; set; }
        public virtual DbSet<PowerReading22> PowerReading22 { get; set; }
        public virtual DbSet<PowerReading23> PowerReading23 { get; set; }
        public virtual DbSet<PowerStation> PowerStations { get; set; }
    }
}
