//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPowerStations
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerReading20
    {
        public int ID { get; set; }
        public byte ReadingMinute { get; set; }
        public byte ReadingSecond { get; set; }
        public decimal Station01PowerUsage { get; set; }
        public decimal Station02PowerUsage { get; set; }
        public decimal Station03PowerUsage { get; set; }
        public decimal Station04PowerUsage { get; set; }
        public decimal Station05PowerUsage { get; set; }
        public decimal Station06PowerUsage { get; set; }
        public decimal Station07PowerUsage { get; set; }
        public decimal Station08PowerUsage { get; set; }
        public decimal Station09PowerUsage { get; set; }
        public decimal Station10PowerUsage { get; set; }
    }
}
